<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNEa8iYM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNEa8iYM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNEa8iYM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNEa8iYM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNEa8iYM\App_KernelDevDebugContainer([
    'container.build_hash' => 'NEa8iYM',
    'container.build_id' => 'fabcedf3',
    'container.build_time' => 1712078140,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNEa8iYM');
